services:
  postgres:
    image: pgvector/pgvector:0.8.4-pg18
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: chatrpg
      POSTGRES_DB: chatrpg
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
